FROM    ubuntu
LABEL   maintainer="Elizabeth" ApplicationName="Sample Docker Image" company="New Era"
WORKDIR /new-era
RUN     apt-get -y update && apt-get -y install nginx
ENV     VAR_ NAME=sample-env
CMD     [ "sleep", "3600" ]
