name: Published Docker Image

on: [push]

jobs:
 push_image_to_registry:
  name: Push Docker Image to registry
  runs-on: ubuntu-latest
  steps:
  - name: Check out the repo
    uses: actions/checkout@v3.5.2
  - name: Log in to Docker Hub
uses: docker/login-action@v2.1.0 
 with:
 username:
   password: 
 
