name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
      - name: Checkout code
      uses: actions/checkout@v2
      - name: Build
        run: |
      echo "Docker Build..."
    - name: Tag
    run: |
    echo "Docker Tag..."
  - name: Push
  run: |
  echo "Docker Push..."
